name: auth-pipeline

on:
  push:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build-deploy:
    runs-on: self-hosted
    defaults:
      run:
        shell: powershell

    steps:
      # 1. Checkout source code
      - name: Checkout codewsw
        uses: actions/checkout@v3

      # 2. Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # 3. Log in to DockerHub
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 4. Build and push Docker image
      - name: Build and push Docker image

        shell: powershell
        run: |
          docker build -t hritik2345/auth:${{ github.sha }} .
          docker push hritik2345/auth:${{ github.sha }}

      # 5. Checkout infra repo (manifests)
      - name: Checkout infra repo
        uses: actions/checkout@v3
        with:
          repository: Hritik-choukikar/secret
          ref: main
          token: ${{ secrets.GH_PAT3 }}
          path: infra-repo

      # 6. Debug manifest paths
      - name: Debug infra repo files
        shell: powershell
        run: |
          ls -R infra-repo

      # 7. Set up kubectla
      - name: Set up kubectlas
        uses: azure/setup-kubectl@v3
        with:
          version: "latest"

      # 8. Configure kubeconfig (single source of truth)
      - name: Configure kubeconfig 
        shell: powershell 
        run: | 
          if (-Not (Test-Path "$HOME\.kube")) { New-Item -ItemType Directory -Force -Path "$HOME\.kube" | Out-Null } [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String("${{ secrets.KUBECON }}")) | Set-Content -Path "$HOME\.kube\config" -Encoding UTF8

      - name: Verify cluster connections
        shell: powershell
        run: |
          kubectl config current-context
          kubectl get namespaces

      - name: Replace image placeholdersss
        shell: powershell
        run: |
          (Get-Content infra-repo\infra-repo\k8s\deployment.yaml) -replace 'IMAGE_PLACEHOLDER', 'hritik2345/auth:${{ github.sha }}' | Set-Content infra-repo\infra-repo\k8s\deployment.yaml

      # 10. Apply Kubernetes manifests
      - name: Apply Kubernetes manifests
        shell: powershell
        run: |
          kubectl delete pods --all
          kubectl delete services --all
          kubectl apply -f infra-repo/infra-repo/k8s/ConfigMap.yaml 
          kubectl apply -f infra-repo/infra-repo/k8s/secrets.yaml
          kubectl apply -f infra-repo/infra-repo/k8s/deployment.yaml --validate=false
          kubectl apply -f infra-repo/infra-repo/k8s/services.yaml
