name: auth_pipeline

on:
  push:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout source code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # 3. Log in to DockerHub
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 4. Build and push Docker image
      - name: Build and push Docker image
        run: |
          docker build -t hritik2345/auth:${{ github.sha }} .
          docker push hritik2345/auth:${{ github.sha }}

      # 5. Checkout infra repo (manifests)
      - name: Checkout infra repo
        uses: actions/checkout@v3
        with:
          repository: Hritik-choukikar/secret
          ref: main
          token: ${{ secrets.GH_PAT3 }}
          path: infra-repo

      # 6. Debug manifest paths
      - name: List infra repo files
        run: ls -R infra-repo

      # 7. Set up kubectl
      - name: Set up kubectlgiddddd
        uses: azure/setup-kubectl@v3
        with:
          version: "latest"

      # 8. Configure kubeconfig
      - name: Configure kubeconfig
        run: |
          echo "${{ secrets.KUBECONFIG3 }}" > kubeconfig.yaml
          export KUBECONFIG=kubeconfig.yaml
      - name: Check kubeconfig file exists
        run: |
          ls -l kubeconfig.yaml 
          head -n 20 kubeconfig.yaml
      - name: List infra repo files
        run: ls -R infra-repo

      # 9. Apply Kubernetes manifests
      - name: Apply Kubernetes manifestss
        run: |
          sed -i "s|IMAGE_PLACEHOLDER|hritik2345/auth:${{ github.sha }}|g" infra-repo/infra-repo/k8s/deployment.yaml 
          kubectl apply -f infra-repo/infra-repo/k8s/deployment.yaml --validate=false

          kubectl apply -f infra-repo/infra-repo/k8s/services.yaml 
          kubectl rollout status deployment/auth-deployment -n default
