name: auth_pipeline
on:
  push:
    branches: ["main"]
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: chekkkk
        run: echo djbkd

      - name: check out user
        uses: actions/checkout@v3

      - name: setup docker
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: chekkkk
        run: echo djbkd

      - name: Build and push Docker image
        run: |
          docker build -t hritik2345/auth:${{ github.sha }} . 
          docker push hritik2345/auth:${{ github.sha }}

      - name: Checkout secret repo (infra configs)
        uses: actions/checkout@v3
        with:
          repository: Hritik-choukikar/secret
          ref: main
          token: ${{ secrets.GH_PAT3 }}
          path: infra-repo

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: "latest"
      - name: Configure kubeconfigd    
        run: |
          echo "${{ secrets.KUBECONFIG }}" > kubeconfig.yaml 
          export KUBECONFIG=kubeconfig.yaml
      - name: Apply Kubernetes manifests
        run: | 
          # Replace image tag dynamically in deployment.yaml beforffe applying 
          sed -i "s|IMAGE_PLACEHOLDER|hritik2345/auth:${{ github.sha }}|g" infra-repo/deployment.yaml 
          kubectl apply -f infra-repo/deployment.yaml 
          kubectl apply -f infra-repo/services.yaml
          kubectl rollout status deployment/auth-deployment -n default
